// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "gojiko api": Application User Types
//
// Command:
// $ goagen
// --design=github.com/craftone/gojiko/goa/design
// --out=$(GOPATH)/src/github.com/craftone/gojiko/goa
// --regen=true
// --version=v1.3.0

package client

import (
	"github.com/goadesign/goa"
)

// fTEID user type.
type fTEID struct {
	IPv4Addr *string `form:"IPv4 Addr,omitempty" json:"IPv4 Addr,omitempty" xml:"IPv4 Addr,omitempty"`
	TEID     *string `form:"TEID,omitempty" json:"TEID,omitempty" xml:"TEID,omitempty"`
}

// Validate validates the fTEID type instance.
func (ut *fTEID) Validate() (err error) {
	if ut.IPv4Addr != nil {
		if err2 := goa.ValidateFormat(goa.FormatIPv4, *ut.IPv4Addr); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`request.IPv4 Addr`, *ut.IPv4Addr, goa.FormatIPv4, err2))
		}
	}
	if ut.TEID != nil {
		if ok := goa.ValidatePattern(`^0x[0-9A-F]{8}$`, *ut.TEID); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`request.TEID`, *ut.TEID, `^0x[0-9A-F]{8}$`))
		}
	}
	return
}

// Publicize creates FTEID from fTEID
func (ut *fTEID) Publicize() *FTEID {
	var pub FTEID
	if ut.IPv4Addr != nil {
		pub.IPv4Addr = ut.IPv4Addr
	}
	if ut.TEID != nil {
		pub.TEID = ut.TEID
	}
	return &pub
}

// FTEID user type.
type FTEID struct {
	IPv4Addr *string `form:"IPv4 Addr,omitempty" json:"IPv4 Addr,omitempty" xml:"IPv4 Addr,omitempty"`
	TEID     *string `form:"TEID,omitempty" json:"TEID,omitempty" xml:"TEID,omitempty"`
}

// Validate validates the FTEID type instance.
func (ut *FTEID) Validate() (err error) {
	if ut.IPv4Addr != nil {
		if err2 := goa.ValidateFormat(goa.FormatIPv4, *ut.IPv4Addr); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`type.IPv4 Addr`, *ut.IPv4Addr, goa.FormatIPv4, err2))
		}
	}
	if ut.TEID != nil {
		if ok := goa.ValidatePattern(`^0x[0-9A-F]{8}$`, *ut.TEID); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`type.TEID`, *ut.TEID, `^0x[0-9A-F]{8}$`))
		}
	}
	return
}

// gtpSessionFTEIDs user type.
type gtpSessionFTEIDs struct {
	PgwCtrlFTEID *fTEID `form:"pgwCtrlFTEID,omitempty" json:"pgwCtrlFTEID,omitempty" xml:"pgwCtrlFTEID,omitempty"`
	PgwDataFTEID *fTEID `form:"pgwDataFTEID,omitempty" json:"pgwDataFTEID,omitempty" xml:"pgwDataFTEID,omitempty"`
	SgwCtrlFTEID *fTEID `form:"sgwCtrlFTEID,omitempty" json:"sgwCtrlFTEID,omitempty" xml:"sgwCtrlFTEID,omitempty"`
	SgwDataFTEID *fTEID `form:"sgwDataFTEID,omitempty" json:"sgwDataFTEID,omitempty" xml:"sgwDataFTEID,omitempty"`
}

// Validate validates the gtpSessionFTEIDs type instance.
func (ut *gtpSessionFTEIDs) Validate() (err error) {
	if ut.PgwCtrlFTEID != nil {
		if err2 := ut.PgwCtrlFTEID.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if ut.PgwDataFTEID != nil {
		if err2 := ut.PgwDataFTEID.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if ut.SgwCtrlFTEID != nil {
		if err2 := ut.SgwCtrlFTEID.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if ut.SgwDataFTEID != nil {
		if err2 := ut.SgwDataFTEID.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// Publicize creates GtpSessionFTEIDs from gtpSessionFTEIDs
func (ut *gtpSessionFTEIDs) Publicize() *GtpSessionFTEIDs {
	var pub GtpSessionFTEIDs
	if ut.PgwCtrlFTEID != nil {
		pub.PgwCtrlFTEID = ut.PgwCtrlFTEID.Publicize()
	}
	if ut.PgwDataFTEID != nil {
		pub.PgwDataFTEID = ut.PgwDataFTEID.Publicize()
	}
	if ut.SgwCtrlFTEID != nil {
		pub.SgwCtrlFTEID = ut.SgwCtrlFTEID.Publicize()
	}
	if ut.SgwDataFTEID != nil {
		pub.SgwDataFTEID = ut.SgwDataFTEID.Publicize()
	}
	return &pub
}

// GtpSessionFTEIDs user type.
type GtpSessionFTEIDs struct {
	PgwCtrlFTEID *FTEID `form:"pgwCtrlFTEID,omitempty" json:"pgwCtrlFTEID,omitempty" xml:"pgwCtrlFTEID,omitempty"`
	PgwDataFTEID *FTEID `form:"pgwDataFTEID,omitempty" json:"pgwDataFTEID,omitempty" xml:"pgwDataFTEID,omitempty"`
	SgwCtrlFTEID *FTEID `form:"sgwCtrlFTEID,omitempty" json:"sgwCtrlFTEID,omitempty" xml:"sgwCtrlFTEID,omitempty"`
	SgwDataFTEID *FTEID `form:"sgwDataFTEID,omitempty" json:"sgwDataFTEID,omitempty" xml:"sgwDataFTEID,omitempty"`
}

// Validate validates the GtpSessionFTEIDs type instance.
func (ut *GtpSessionFTEIDs) Validate() (err error) {
	if ut.PgwCtrlFTEID != nil {
		if err2 := ut.PgwCtrlFTEID.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if ut.PgwDataFTEID != nil {
		if err2 := ut.PgwDataFTEID.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if ut.SgwCtrlFTEID != nil {
		if err2 := ut.SgwCtrlFTEID.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if ut.SgwDataFTEID != nil {
		if err2 := ut.SgwDataFTEID.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}
