// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "gojiko api": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/craftone/gojiko/goa/design
// --out=$(GOPATH)\src\github.com\craftone\gojiko\goa
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
	"strconv"
)

// CreateGtpsessionContext provides the gtpsession create action context.
type CreateGtpsessionContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	SgwAddr string
	Payload *CreateGtpsessionPayload
}

// NewCreateGtpsessionContext parses the incoming request URL and body, performs validations and creates the
// context used by the gtpsession controller create action.
func NewCreateGtpsessionContext(ctx context.Context, r *http.Request, service *goa.Service) (*CreateGtpsessionContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := CreateGtpsessionContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramSgwAddr := req.Params["sgwAddr"]
	if len(paramSgwAddr) > 0 {
		rawSgwAddr := paramSgwAddr[0]
		rctx.SgwAddr = rawSgwAddr
		if err2 := goa.ValidateFormat(goa.FormatIPv4, rctx.SgwAddr); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`sgwAddr`, rctx.SgwAddr, goa.FormatIPv4, err2))
		}
	}
	return &rctx, err
}

// createGtpsessionPayload is the gtpsession create action payload.
type createGtpsessionPayload struct {
	// Access Point Name
	Apn *string `form:"apn,omitempty" json:"apn,omitempty" yaml:"apn,omitempty" xml:"apn,omitempty"`
	// EPS Bearer ID
	Ebi  *int    `form:"ebi,omitempty" json:"ebi,omitempty" yaml:"ebi,omitempty" xml:"ebi,omitempty"`
	Ecgi *ecgi   `form:"ecgi,omitempty" json:"ecgi,omitempty" yaml:"ecgi,omitempty" xml:"ecgi,omitempty"`
	Imsi *string `form:"imsi,omitempty" json:"imsi,omitempty" yaml:"imsi,omitempty" xml:"imsi,omitempty"`
	// Mobile Country Code
	Mcc *string `form:"mcc,omitempty" json:"mcc,omitempty" yaml:"mcc,omitempty" xml:"mcc,omitempty"`
	// Mobile Equipment Identifier
	Mei *string `form:"mei,omitempty" json:"mei,omitempty" yaml:"mei,omitempty" xml:"mei,omitempty"`
	// Mobile Network Code
	Mnc    *string `form:"mnc,omitempty" json:"mnc,omitempty" yaml:"mnc,omitempty" xml:"mnc,omitempty"`
	Msisdn *string `form:"msisdn,omitempty" json:"msisdn,omitempty" yaml:"msisdn,omitempty" xml:"msisdn,omitempty"`
	// Specify when using external pseudo SGW-DATA
	PseudoSgwDataAddr *string `form:"pseudoSgwDataAddr,omitempty" json:"pseudoSgwDataAddr,omitempty" yaml:"pseudoSgwDataAddr,omitempty" xml:"pseudoSgwDataAddr,omitempty"`
	// Specify when using external pseudo SGW-DATA which tunnel's TEID has already determined.
	// If 0 is specified, TEID is generated automatically.
	// If pseudoSgwDataAddr is not specified, this attribute is ignored.
	PseudoSgwDataTEID *int `form:"pseudoSgwDataTEID,omitempty" json:"pseudoSgwDataTEID,omitempty" yaml:"pseudoSgwDataTEID,omitempty" xml:"pseudoSgwDataTEID,omitempty"`
	// Default is 6 : E-UTRAN (WB-E-UTRAN)
	RatTypeValue *int `form:"ratTypeValue,omitempty" json:"ratTypeValue,omitempty" yaml:"ratTypeValue,omitempty" xml:"ratTypeValue,omitempty"`
	Tai          *tai `form:"tai,omitempty" json:"tai,omitempty" yaml:"tai,omitempty" xml:"tai,omitempty"`
}

// Finalize sets the default values defined in the design.
func (payload *createGtpsessionPayload) Finalize() {
	var defaultEbi = 5
	if payload.Ebi == nil {
		payload.Ebi = &defaultEbi
	}
	if payload.Ecgi != nil {
		var defaultEci = 1
		if payload.Ecgi.Eci == nil {
			payload.Ecgi.Eci = &defaultEci
		}
		var defaultMcc = "440"
		if payload.Ecgi.Mcc == nil {
			payload.Ecgi.Mcc = &defaultMcc
		}
		var defaultMnc = "10"
		if payload.Ecgi.Mnc == nil {
			payload.Ecgi.Mnc = &defaultMnc
		}
	}
	var defaultMcc = "440"
	if payload.Mcc == nil {
		payload.Mcc = &defaultMcc
	}
	var defaultMnc = "10"
	if payload.Mnc == nil {
		payload.Mnc = &defaultMnc
	}
	var defaultPseudoSgwDataTEID = 0
	if payload.PseudoSgwDataTEID == nil {
		payload.PseudoSgwDataTEID = &defaultPseudoSgwDataTEID
	}
	var defaultRatTypeValue = 6
	if payload.RatTypeValue == nil {
		payload.RatTypeValue = &defaultRatTypeValue
	}
	if payload.Tai != nil {
		var defaultMcc = "440"
		if payload.Tai.Mcc == nil {
			payload.Tai.Mcc = &defaultMcc
		}
		var defaultMnc = "10"
		if payload.Tai.Mnc == nil {
			payload.Tai.Mnc = &defaultMnc
		}
		var defaultTac = 1
		if payload.Tai.Tac == nil {
			payload.Tai.Tac = &defaultTac
		}
	}
}

// Validate runs the validation rules defined in the design.
func (payload *createGtpsessionPayload) Validate() (err error) {
	if payload.Apn == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "apn"))
	}
	if payload.Mcc == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "mcc"))
	}
	if payload.Mnc == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "mnc"))
	}
	if payload.Msisdn == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "msisdn"))
	}
	if payload.Mei == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "mei"))
	}
	if payload.Imsi == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "imsi"))
	}
	if payload.Ebi == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "ebi"))
	}
	if payload.Apn != nil {
		if err2 := goa.ValidateFormat(goa.FormatHostname, *payload.Apn); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`raw.apn`, *payload.Apn, goa.FormatHostname, err2))
		}
	}
	if payload.Ebi != nil {
		if *payload.Ebi < 5 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.ebi`, *payload.Ebi, 5, true))
		}
	}
	if payload.Ebi != nil {
		if *payload.Ebi > 15 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.ebi`, *payload.Ebi, 15, false))
		}
	}
	if payload.Ecgi != nil {
		if err2 := payload.Ecgi.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if payload.Imsi != nil {
		if ok := goa.ValidatePattern(`^[0-9]{14,15}$`, *payload.Imsi); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`raw.imsi`, *payload.Imsi, `^[0-9]{14,15}$`))
		}
	}
	if payload.Mcc != nil {
		if ok := goa.ValidatePattern(`^[0-9]{3}$`, *payload.Mcc); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`raw.mcc`, *payload.Mcc, `^[0-9]{3}$`))
		}
	}
	if payload.Mei != nil {
		if ok := goa.ValidatePattern(`^[0-9]{15,16}$`, *payload.Mei); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`raw.mei`, *payload.Mei, `^[0-9]{15,16}$`))
		}
	}
	if payload.Mnc != nil {
		if ok := goa.ValidatePattern(`^[0-9]{2,3}$`, *payload.Mnc); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`raw.mnc`, *payload.Mnc, `^[0-9]{2,3}$`))
		}
	}
	if payload.Msisdn != nil {
		if ok := goa.ValidatePattern(`^[0-9]{12,15}$`, *payload.Msisdn); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`raw.msisdn`, *payload.Msisdn, `^[0-9]{12,15}$`))
		}
	}
	if payload.PseudoSgwDataAddr != nil {
		if err2 := goa.ValidateFormat(goa.FormatIPv4, *payload.PseudoSgwDataAddr); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`raw.pseudoSgwDataAddr`, *payload.PseudoSgwDataAddr, goa.FormatIPv4, err2))
		}
	}
	if payload.PseudoSgwDataTEID != nil {
		if *payload.PseudoSgwDataTEID < 0 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.pseudoSgwDataTEID`, *payload.PseudoSgwDataTEID, 0, true))
		}
	}
	if payload.PseudoSgwDataTEID != nil {
		if *payload.PseudoSgwDataTEID > 4294967295 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.pseudoSgwDataTEID`, *payload.PseudoSgwDataTEID, 4294967295, false))
		}
	}
	if payload.RatTypeValue != nil {
		if *payload.RatTypeValue < 0 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.ratTypeValue`, *payload.RatTypeValue, 0, true))
		}
	}
	if payload.RatTypeValue != nil {
		if *payload.RatTypeValue > 255 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.ratTypeValue`, *payload.RatTypeValue, 255, false))
		}
	}
	if payload.Tai != nil {
		if err2 := payload.Tai.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// Publicize creates CreateGtpsessionPayload from createGtpsessionPayload
func (payload *createGtpsessionPayload) Publicize() *CreateGtpsessionPayload {
	var pub CreateGtpsessionPayload
	if payload.Apn != nil {
		pub.Apn = *payload.Apn
	}
	if payload.Ebi != nil {
		pub.Ebi = *payload.Ebi
	}
	if payload.Ecgi != nil {
		pub.Ecgi = payload.Ecgi.Publicize()
	}
	if payload.Imsi != nil {
		pub.Imsi = *payload.Imsi
	}
	if payload.Mcc != nil {
		pub.Mcc = *payload.Mcc
	}
	if payload.Mei != nil {
		pub.Mei = *payload.Mei
	}
	if payload.Mnc != nil {
		pub.Mnc = *payload.Mnc
	}
	if payload.Msisdn != nil {
		pub.Msisdn = *payload.Msisdn
	}
	if payload.PseudoSgwDataAddr != nil {
		pub.PseudoSgwDataAddr = payload.PseudoSgwDataAddr
	}
	if payload.PseudoSgwDataTEID != nil {
		pub.PseudoSgwDataTEID = *payload.PseudoSgwDataTEID
	}
	if payload.RatTypeValue != nil {
		pub.RatTypeValue = *payload.RatTypeValue
	}
	if payload.Tai != nil {
		pub.Tai = payload.Tai.Publicize()
	}
	return &pub
}

// CreateGtpsessionPayload is the gtpsession create action payload.
type CreateGtpsessionPayload struct {
	// Access Point Name
	Apn string `form:"apn" json:"apn" yaml:"apn" xml:"apn"`
	// EPS Bearer ID
	Ebi  int    `form:"ebi" json:"ebi" yaml:"ebi" xml:"ebi"`
	Ecgi *Ecgi  `form:"ecgi,omitempty" json:"ecgi,omitempty" yaml:"ecgi,omitempty" xml:"ecgi,omitempty"`
	Imsi string `form:"imsi" json:"imsi" yaml:"imsi" xml:"imsi"`
	// Mobile Country Code
	Mcc string `form:"mcc" json:"mcc" yaml:"mcc" xml:"mcc"`
	// Mobile Equipment Identifier
	Mei string `form:"mei" json:"mei" yaml:"mei" xml:"mei"`
	// Mobile Network Code
	Mnc    string `form:"mnc" json:"mnc" yaml:"mnc" xml:"mnc"`
	Msisdn string `form:"msisdn" json:"msisdn" yaml:"msisdn" xml:"msisdn"`
	// Specify when using external pseudo SGW-DATA
	PseudoSgwDataAddr *string `form:"pseudoSgwDataAddr,omitempty" json:"pseudoSgwDataAddr,omitempty" yaml:"pseudoSgwDataAddr,omitempty" xml:"pseudoSgwDataAddr,omitempty"`
	// Specify when using external pseudo SGW-DATA which tunnel's TEID has already determined.
	// If 0 is specified, TEID is generated automatically.
	// If pseudoSgwDataAddr is not specified, this attribute is ignored.
	PseudoSgwDataTEID int `form:"pseudoSgwDataTEID" json:"pseudoSgwDataTEID" yaml:"pseudoSgwDataTEID" xml:"pseudoSgwDataTEID"`
	// Default is 6 : E-UTRAN (WB-E-UTRAN)
	RatTypeValue int  `form:"ratTypeValue" json:"ratTypeValue" yaml:"ratTypeValue" xml:"ratTypeValue"`
	Tai          *Tai `form:"tai,omitempty" json:"tai,omitempty" yaml:"tai,omitempty" xml:"tai,omitempty"`
}

// Validate runs the validation rules defined in the design.
func (payload *CreateGtpsessionPayload) Validate() (err error) {
	if payload.Apn == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "apn"))
	}
	if payload.Mcc == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "mcc"))
	}
	if payload.Mnc == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "mnc"))
	}
	if payload.Msisdn == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "msisdn"))
	}
	if payload.Mei == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "mei"))
	}
	if payload.Imsi == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "imsi"))
	}

	if err2 := goa.ValidateFormat(goa.FormatHostname, payload.Apn); err2 != nil {
		err = goa.MergeErrors(err, goa.InvalidFormatError(`raw.apn`, payload.Apn, goa.FormatHostname, err2))
	}
	if payload.Ebi < 5 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.ebi`, payload.Ebi, 5, true))
	}
	if payload.Ebi > 15 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.ebi`, payload.Ebi, 15, false))
	}
	if payload.Ecgi != nil {
		if err2 := payload.Ecgi.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if ok := goa.ValidatePattern(`^[0-9]{14,15}$`, payload.Imsi); !ok {
		err = goa.MergeErrors(err, goa.InvalidPatternError(`raw.imsi`, payload.Imsi, `^[0-9]{14,15}$`))
	}
	if ok := goa.ValidatePattern(`^[0-9]{3}$`, payload.Mcc); !ok {
		err = goa.MergeErrors(err, goa.InvalidPatternError(`raw.mcc`, payload.Mcc, `^[0-9]{3}$`))
	}
	if ok := goa.ValidatePattern(`^[0-9]{15,16}$`, payload.Mei); !ok {
		err = goa.MergeErrors(err, goa.InvalidPatternError(`raw.mei`, payload.Mei, `^[0-9]{15,16}$`))
	}
	if ok := goa.ValidatePattern(`^[0-9]{2,3}$`, payload.Mnc); !ok {
		err = goa.MergeErrors(err, goa.InvalidPatternError(`raw.mnc`, payload.Mnc, `^[0-9]{2,3}$`))
	}
	if ok := goa.ValidatePattern(`^[0-9]{12,15}$`, payload.Msisdn); !ok {
		err = goa.MergeErrors(err, goa.InvalidPatternError(`raw.msisdn`, payload.Msisdn, `^[0-9]{12,15}$`))
	}
	if payload.PseudoSgwDataAddr != nil {
		if err2 := goa.ValidateFormat(goa.FormatIPv4, *payload.PseudoSgwDataAddr); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`raw.pseudoSgwDataAddr`, *payload.PseudoSgwDataAddr, goa.FormatIPv4, err2))
		}
	}
	if payload.PseudoSgwDataTEID < 0 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.pseudoSgwDataTEID`, payload.PseudoSgwDataTEID, 0, true))
	}
	if payload.PseudoSgwDataTEID > 4294967295 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.pseudoSgwDataTEID`, payload.PseudoSgwDataTEID, 4294967295, false))
	}
	if payload.RatTypeValue < 0 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.ratTypeValue`, payload.RatTypeValue, 0, true))
	}
	if payload.RatTypeValue > 255 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.ratTypeValue`, payload.RatTypeValue, 255, false))
	}
	if payload.Tai != nil {
		if err2 := payload.Tai.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// OK sends a HTTP response with status code 200.
func (ctx *CreateGtpsessionContext) OK(r *Gtpv2cCsres) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.gtpv2c.csres+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *CreateGtpsessionContext) BadRequest(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *CreateGtpsessionContext) NotFound(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// Conflict sends a HTTP response with status code 409.
func (ctx *CreateGtpsessionContext) Conflict(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 409, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *CreateGtpsessionContext) InternalServerError(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 500, r)
}

// ServiceUnavailable sends a HTTP response with status code 503.
func (ctx *CreateGtpsessionContext) ServiceUnavailable(r *Gtpv2cCause) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.gtpv2c.cause+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 503, r)
}

// GatewayTimeout sends a HTTP response with status code 504.
func (ctx *CreateGtpsessionContext) GatewayTimeout(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 504, r)
}

// DeleteByIMSIandEBIGtpsessionContext provides the gtpsession deleteByIMSIandEBI action context.
type DeleteByIMSIandEBIGtpsessionContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Ebi     int
	Imsi    string
	SgwAddr string
}

// NewDeleteByIMSIandEBIGtpsessionContext parses the incoming request URL and body, performs validations and creates the
// context used by the gtpsession controller deleteByIMSIandEBI action.
func NewDeleteByIMSIandEBIGtpsessionContext(ctx context.Context, r *http.Request, service *goa.Service) (*DeleteByIMSIandEBIGtpsessionContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := DeleteByIMSIandEBIGtpsessionContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramEbi := req.Params["ebi"]
	if len(paramEbi) == 0 {
		rctx.Ebi = 5
	} else {
		rawEbi := paramEbi[0]
		if ebi, err2 := strconv.Atoi(rawEbi); err2 == nil {
			rctx.Ebi = ebi
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("ebi", rawEbi, "integer"))
		}
		if rctx.Ebi < 5 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`ebi`, rctx.Ebi, 5, true))
		}
		if rctx.Ebi > 15 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`ebi`, rctx.Ebi, 15, false))
		}
	}
	paramImsi := req.Params["imsi"]
	if len(paramImsi) > 0 {
		rawImsi := paramImsi[0]
		rctx.Imsi = rawImsi
		if ok := goa.ValidatePattern(`^[0-9]{14,15}$`, rctx.Imsi); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`imsi`, rctx.Imsi, `^[0-9]{14,15}$`))
		}
	}
	paramSgwAddr := req.Params["sgwAddr"]
	if len(paramSgwAddr) > 0 {
		rawSgwAddr := paramSgwAddr[0]
		rctx.SgwAddr = rawSgwAddr
		if err2 := goa.ValidateFormat(goa.FormatIPv4, rctx.SgwAddr); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`sgwAddr`, rctx.SgwAddr, goa.FormatIPv4, err2))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *DeleteByIMSIandEBIGtpsessionContext) OK(r *Gtpv2cCause) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.gtpv2c.cause+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *DeleteByIMSIandEBIGtpsessionContext) NotFound(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// Conflict sends a HTTP response with status code 409.
func (ctx *DeleteByIMSIandEBIGtpsessionContext) Conflict(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 409, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *DeleteByIMSIandEBIGtpsessionContext) InternalServerError(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 500, r)
}

// ShowByIDGtpsessionContext provides the gtpsession showByID action context.
type ShowByIDGtpsessionContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	SgwAddr string
	Sid     int
}

// NewShowByIDGtpsessionContext parses the incoming request URL and body, performs validations and creates the
// context used by the gtpsession controller showByID action.
func NewShowByIDGtpsessionContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowByIDGtpsessionContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowByIDGtpsessionContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramSgwAddr := req.Params["sgwAddr"]
	if len(paramSgwAddr) > 0 {
		rawSgwAddr := paramSgwAddr[0]
		rctx.SgwAddr = rawSgwAddr
		if err2 := goa.ValidateFormat(goa.FormatIPv4, rctx.SgwAddr); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`sgwAddr`, rctx.SgwAddr, goa.FormatIPv4, err2))
		}
	}
	paramSid := req.Params["sid"]
	if len(paramSid) > 0 {
		rawSid := paramSid[0]
		if sid, err2 := strconv.Atoi(rawSid); err2 == nil {
			rctx.Sid = sid
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("sid", rawSid, "integer"))
		}
		if rctx.Sid < 0 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`sid`, rctx.Sid, 0, true))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowByIDGtpsessionContext) OK(r *Gtpsession) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.gtpsession+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ShowByIDGtpsessionContext) NotFound(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// ShowByIMSIandEBIGtpsessionContext provides the gtpsession showByIMSIandEBI action context.
type ShowByIMSIandEBIGtpsessionContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Ebi     int
	Imsi    string
	SgwAddr string
}

// NewShowByIMSIandEBIGtpsessionContext parses the incoming request URL and body, performs validations and creates the
// context used by the gtpsession controller showByIMSIandEBI action.
func NewShowByIMSIandEBIGtpsessionContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowByIMSIandEBIGtpsessionContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowByIMSIandEBIGtpsessionContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramEbi := req.Params["ebi"]
	if len(paramEbi) == 0 {
		rctx.Ebi = 5
	} else {
		rawEbi := paramEbi[0]
		if ebi, err2 := strconv.Atoi(rawEbi); err2 == nil {
			rctx.Ebi = ebi
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("ebi", rawEbi, "integer"))
		}
		if rctx.Ebi < 5 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`ebi`, rctx.Ebi, 5, true))
		}
		if rctx.Ebi > 15 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`ebi`, rctx.Ebi, 15, false))
		}
	}
	paramImsi := req.Params["imsi"]
	if len(paramImsi) > 0 {
		rawImsi := paramImsi[0]
		rctx.Imsi = rawImsi
		if ok := goa.ValidatePattern(`^[0-9]{14,15}$`, rctx.Imsi); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`imsi`, rctx.Imsi, `^[0-9]{14,15}$`))
		}
	}
	paramSgwAddr := req.Params["sgwAddr"]
	if len(paramSgwAddr) > 0 {
		rawSgwAddr := paramSgwAddr[0]
		rctx.SgwAddr = rawSgwAddr
		if err2 := goa.ValidateFormat(goa.FormatIPv4, rctx.SgwAddr); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`sgwAddr`, rctx.SgwAddr, goa.FormatIPv4, err2))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowByIMSIandEBIGtpsessionContext) OK(r *Gtpsession) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.gtpsession+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ShowByIMSIandEBIGtpsessionContext) NotFound(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// TrackingAreaUpdateWithoutSgwRelocationGtpsessionContext provides the gtpsession trackingAreaUpdateWithoutSgwRelocation action context.
type TrackingAreaUpdateWithoutSgwRelocationGtpsessionContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Ebi     int
	Imsi    string
	SgwAddr string
	Payload *TrackingAreaUpdateWithoutSgwRelocationGtpsessionPayload
}

// NewTrackingAreaUpdateWithoutSgwRelocationGtpsessionContext parses the incoming request URL and body, performs validations and creates the
// context used by the gtpsession controller trackingAreaUpdateWithoutSgwRelocation action.
func NewTrackingAreaUpdateWithoutSgwRelocationGtpsessionContext(ctx context.Context, r *http.Request, service *goa.Service) (*TrackingAreaUpdateWithoutSgwRelocationGtpsessionContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := TrackingAreaUpdateWithoutSgwRelocationGtpsessionContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramEbi := req.Params["ebi"]
	if len(paramEbi) == 0 {
		rctx.Ebi = 5
	} else {
		rawEbi := paramEbi[0]
		if ebi, err2 := strconv.Atoi(rawEbi); err2 == nil {
			rctx.Ebi = ebi
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("ebi", rawEbi, "integer"))
		}
		if rctx.Ebi < 5 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`ebi`, rctx.Ebi, 5, true))
		}
		if rctx.Ebi > 15 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`ebi`, rctx.Ebi, 15, false))
		}
	}
	paramImsi := req.Params["imsi"]
	if len(paramImsi) > 0 {
		rawImsi := paramImsi[0]
		rctx.Imsi = rawImsi
		if ok := goa.ValidatePattern(`^[0-9]{14,15}$`, rctx.Imsi); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`imsi`, rctx.Imsi, `^[0-9]{14,15}$`))
		}
	}
	paramSgwAddr := req.Params["sgwAddr"]
	if len(paramSgwAddr) > 0 {
		rawSgwAddr := paramSgwAddr[0]
		rctx.SgwAddr = rawSgwAddr
		if err2 := goa.ValidateFormat(goa.FormatIPv4, rctx.SgwAddr); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`sgwAddr`, rctx.SgwAddr, goa.FormatIPv4, err2))
		}
	}
	return &rctx, err
}

// trackingAreaUpdateWithoutSgwRelocationGtpsessionPayload is the gtpsession trackingAreaUpdateWithoutSgwRelocation action payload.
type trackingAreaUpdateWithoutSgwRelocationGtpsessionPayload struct {
	Ecgi *ecgi `form:"ecgi,omitempty" json:"ecgi,omitempty" yaml:"ecgi,omitempty" xml:"ecgi,omitempty"`
	// Default is 6 : E-UTRAN (WB-E-UTRAN)
	RatTypeValue *int `form:"ratTypeValue,omitempty" json:"ratTypeValue,omitempty" yaml:"ratTypeValue,omitempty" xml:"ratTypeValue,omitempty"`
	Tai          *tai `form:"tai,omitempty" json:"tai,omitempty" yaml:"tai,omitempty" xml:"tai,omitempty"`
}

// Finalize sets the default values defined in the design.
func (payload *trackingAreaUpdateWithoutSgwRelocationGtpsessionPayload) Finalize() {
	if payload.Ecgi != nil {
		var defaultEci = 1
		if payload.Ecgi.Eci == nil {
			payload.Ecgi.Eci = &defaultEci
		}
		var defaultMcc = "440"
		if payload.Ecgi.Mcc == nil {
			payload.Ecgi.Mcc = &defaultMcc
		}
		var defaultMnc = "10"
		if payload.Ecgi.Mnc == nil {
			payload.Ecgi.Mnc = &defaultMnc
		}
	}
	var defaultRatTypeValue = 6
	if payload.RatTypeValue == nil {
		payload.RatTypeValue = &defaultRatTypeValue
	}
	if payload.Tai != nil {
		var defaultMcc = "440"
		if payload.Tai.Mcc == nil {
			payload.Tai.Mcc = &defaultMcc
		}
		var defaultMnc = "10"
		if payload.Tai.Mnc == nil {
			payload.Tai.Mnc = &defaultMnc
		}
		var defaultTac = 1
		if payload.Tai.Tac == nil {
			payload.Tai.Tac = &defaultTac
		}
	}
}

// Validate runs the validation rules defined in the design.
func (payload *trackingAreaUpdateWithoutSgwRelocationGtpsessionPayload) Validate() (err error) {
	if payload.Tai == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "tai"))
	}
	if payload.Ecgi == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "ecgi"))
	}
	if payload.Ecgi != nil {
		if err2 := payload.Ecgi.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if payload.RatTypeValue != nil {
		if *payload.RatTypeValue < 0 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.ratTypeValue`, *payload.RatTypeValue, 0, true))
		}
	}
	if payload.RatTypeValue != nil {
		if *payload.RatTypeValue > 255 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.ratTypeValue`, *payload.RatTypeValue, 255, false))
		}
	}
	if payload.Tai != nil {
		if err2 := payload.Tai.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// Publicize creates TrackingAreaUpdateWithoutSgwRelocationGtpsessionPayload from trackingAreaUpdateWithoutSgwRelocationGtpsessionPayload
func (payload *trackingAreaUpdateWithoutSgwRelocationGtpsessionPayload) Publicize() *TrackingAreaUpdateWithoutSgwRelocationGtpsessionPayload {
	var pub TrackingAreaUpdateWithoutSgwRelocationGtpsessionPayload
	if payload.Ecgi != nil {
		pub.Ecgi = payload.Ecgi.Publicize()
	}
	if payload.RatTypeValue != nil {
		pub.RatTypeValue = *payload.RatTypeValue
	}
	if payload.Tai != nil {
		pub.Tai = payload.Tai.Publicize()
	}
	return &pub
}

// TrackingAreaUpdateWithoutSgwRelocationGtpsessionPayload is the gtpsession trackingAreaUpdateWithoutSgwRelocation action payload.
type TrackingAreaUpdateWithoutSgwRelocationGtpsessionPayload struct {
	Ecgi *Ecgi `form:"ecgi" json:"ecgi" yaml:"ecgi" xml:"ecgi"`
	// Default is 6 : E-UTRAN (WB-E-UTRAN)
	RatTypeValue int  `form:"ratTypeValue" json:"ratTypeValue" yaml:"ratTypeValue" xml:"ratTypeValue"`
	Tai          *Tai `form:"tai" json:"tai" yaml:"tai" xml:"tai"`
}

// Validate runs the validation rules defined in the design.
func (payload *TrackingAreaUpdateWithoutSgwRelocationGtpsessionPayload) Validate() (err error) {
	if payload.Tai == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "tai"))
	}
	if payload.Ecgi == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`raw`, "ecgi"))
	}
	if payload.Ecgi != nil {
		if err2 := payload.Ecgi.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if payload.RatTypeValue < 0 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.ratTypeValue`, payload.RatTypeValue, 0, true))
	}
	if payload.RatTypeValue > 255 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`raw.ratTypeValue`, payload.RatTypeValue, 255, false))
	}
	if payload.Tai != nil {
		if err2 := payload.Tai.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// OK sends a HTTP response with status code 200.
func (ctx *TrackingAreaUpdateWithoutSgwRelocationGtpsessionContext) OK(r *Gtpv2cCsres) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.gtpv2c.csres+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *TrackingAreaUpdateWithoutSgwRelocationGtpsessionContext) BadRequest(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *TrackingAreaUpdateWithoutSgwRelocationGtpsessionContext) NotFound(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// Conflict sends a HTTP response with status code 409.
func (ctx *TrackingAreaUpdateWithoutSgwRelocationGtpsessionContext) Conflict(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 409, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *TrackingAreaUpdateWithoutSgwRelocationGtpsessionContext) InternalServerError(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 500, r)
}

// ServiceUnavailable sends a HTTP response with status code 503.
func (ctx *TrackingAreaUpdateWithoutSgwRelocationGtpsessionContext) ServiceUnavailable(r *Gtpv2cCause) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.gtpv2c.cause+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 503, r)
}

// GatewayTimeout sends a HTTP response with status code 504.
func (ctx *TrackingAreaUpdateWithoutSgwRelocationGtpsessionContext) GatewayTimeout(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 504, r)
}

// CreateUDPEchoFlowByIMSIandEBIContext provides the udpEchoFlowByIMSIandEBI create action context.
type CreateUDPEchoFlowByIMSIandEBIContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Ebi     int
	Imsi    string
	SgwAddr string
	Payload *UDPEchoFlowPayload
}

// NewCreateUDPEchoFlowByIMSIandEBIContext parses the incoming request URL and body, performs validations and creates the
// context used by the udpEchoFlowByIMSIandEBI controller create action.
func NewCreateUDPEchoFlowByIMSIandEBIContext(ctx context.Context, r *http.Request, service *goa.Service) (*CreateUDPEchoFlowByIMSIandEBIContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := CreateUDPEchoFlowByIMSIandEBIContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramEbi := req.Params["ebi"]
	if len(paramEbi) == 0 {
		rctx.Ebi = 5
	} else {
		rawEbi := paramEbi[0]
		if ebi, err2 := strconv.Atoi(rawEbi); err2 == nil {
			rctx.Ebi = ebi
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("ebi", rawEbi, "integer"))
		}
		if rctx.Ebi < 5 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`ebi`, rctx.Ebi, 5, true))
		}
		if rctx.Ebi > 15 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`ebi`, rctx.Ebi, 15, false))
		}
	}
	paramImsi := req.Params["imsi"]
	if len(paramImsi) > 0 {
		rawImsi := paramImsi[0]
		rctx.Imsi = rawImsi
		if ok := goa.ValidatePattern(`^[0-9]{14,15}$`, rctx.Imsi); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`imsi`, rctx.Imsi, `^[0-9]{14,15}$`))
		}
	}
	paramSgwAddr := req.Params["sgwAddr"]
	if len(paramSgwAddr) > 0 {
		rawSgwAddr := paramSgwAddr[0]
		rctx.SgwAddr = rawSgwAddr
		if err2 := goa.ValidateFormat(goa.FormatIPv4, rctx.SgwAddr); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`sgwAddr`, rctx.SgwAddr, goa.FormatIPv4, err2))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *CreateUDPEchoFlowByIMSIandEBIContext) OK(r *Udpechoflow) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.udpechoflow+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKWithStats sends a HTTP response with status code 200.
func (ctx *CreateUDPEchoFlowByIMSIandEBIContext) OKWithStats(r *UdpechoflowWithStats) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.udpechoflow+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *CreateUDPEchoFlowByIMSIandEBIContext) NotFound(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *CreateUDPEchoFlowByIMSIandEBIContext) InternalServerError(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 500, r)
}

// DeleteUDPEchoFlowByIMSIandEBIContext provides the udpEchoFlowByIMSIandEBI delete action context.
type DeleteUDPEchoFlowByIMSIandEBIContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Ebi     int
	Imsi    string
	SgwAddr string
}

// NewDeleteUDPEchoFlowByIMSIandEBIContext parses the incoming request URL and body, performs validations and creates the
// context used by the udpEchoFlowByIMSIandEBI controller delete action.
func NewDeleteUDPEchoFlowByIMSIandEBIContext(ctx context.Context, r *http.Request, service *goa.Service) (*DeleteUDPEchoFlowByIMSIandEBIContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := DeleteUDPEchoFlowByIMSIandEBIContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramEbi := req.Params["ebi"]
	if len(paramEbi) == 0 {
		rctx.Ebi = 5
	} else {
		rawEbi := paramEbi[0]
		if ebi, err2 := strconv.Atoi(rawEbi); err2 == nil {
			rctx.Ebi = ebi
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("ebi", rawEbi, "integer"))
		}
		if rctx.Ebi < 5 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`ebi`, rctx.Ebi, 5, true))
		}
		if rctx.Ebi > 15 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`ebi`, rctx.Ebi, 15, false))
		}
	}
	paramImsi := req.Params["imsi"]
	if len(paramImsi) > 0 {
		rawImsi := paramImsi[0]
		rctx.Imsi = rawImsi
		if ok := goa.ValidatePattern(`^[0-9]{14,15}$`, rctx.Imsi); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`imsi`, rctx.Imsi, `^[0-9]{14,15}$`))
		}
	}
	paramSgwAddr := req.Params["sgwAddr"]
	if len(paramSgwAddr) > 0 {
		rawSgwAddr := paramSgwAddr[0]
		rctx.SgwAddr = rawSgwAddr
		if err2 := goa.ValidateFormat(goa.FormatIPv4, rctx.SgwAddr); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`sgwAddr`, rctx.SgwAddr, goa.FormatIPv4, err2))
		}
	}
	return &rctx, err
}

// OKWithStats sends a HTTP response with status code 200.
func (ctx *DeleteUDPEchoFlowByIMSIandEBIContext) OKWithStats(r *UdpechoflowWithStats) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.udpechoflow+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *DeleteUDPEchoFlowByIMSIandEBIContext) NotFound(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *DeleteUDPEchoFlowByIMSIandEBIContext) InternalServerError(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 500, r)
}

// ShowUDPEchoFlowByIMSIandEBIContext provides the udpEchoFlowByIMSIandEBI show action context.
type ShowUDPEchoFlowByIMSIandEBIContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Ebi     int
	Imsi    string
	SgwAddr string
}

// NewShowUDPEchoFlowByIMSIandEBIContext parses the incoming request URL and body, performs validations and creates the
// context used by the udpEchoFlowByIMSIandEBI controller show action.
func NewShowUDPEchoFlowByIMSIandEBIContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowUDPEchoFlowByIMSIandEBIContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowUDPEchoFlowByIMSIandEBIContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramEbi := req.Params["ebi"]
	if len(paramEbi) == 0 {
		rctx.Ebi = 5
	} else {
		rawEbi := paramEbi[0]
		if ebi, err2 := strconv.Atoi(rawEbi); err2 == nil {
			rctx.Ebi = ebi
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("ebi", rawEbi, "integer"))
		}
		if rctx.Ebi < 5 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`ebi`, rctx.Ebi, 5, true))
		}
		if rctx.Ebi > 15 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`ebi`, rctx.Ebi, 15, false))
		}
	}
	paramImsi := req.Params["imsi"]
	if len(paramImsi) > 0 {
		rawImsi := paramImsi[0]
		rctx.Imsi = rawImsi
		if ok := goa.ValidatePattern(`^[0-9]{14,15}$`, rctx.Imsi); !ok {
			err = goa.MergeErrors(err, goa.InvalidPatternError(`imsi`, rctx.Imsi, `^[0-9]{14,15}$`))
		}
	}
	paramSgwAddr := req.Params["sgwAddr"]
	if len(paramSgwAddr) > 0 {
		rawSgwAddr := paramSgwAddr[0]
		rctx.SgwAddr = rawSgwAddr
		if err2 := goa.ValidateFormat(goa.FormatIPv4, rctx.SgwAddr); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`sgwAddr`, rctx.SgwAddr, goa.FormatIPv4, err2))
		}
	}
	return &rctx, err
}

// OKWithStats sends a HTTP response with status code 200.
func (ctx *ShowUDPEchoFlowByIMSIandEBIContext) OKWithStats(r *UdpechoflowWithStats) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.udpechoflow+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ShowUDPEchoFlowByIMSIandEBIContext) NotFound(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *ShowUDPEchoFlowByIMSIandEBIContext) InternalServerError(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 500, r)
}
