// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "gojiko api": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/craftone/gojiko/goa/design
// --out=$(GOPATH)/src/github.com/craftone/gojiko/goa
// --version=v1.3.0

package app
