@startuml

Client -> API : POST sessions
API -> SgwCtrl : CreateSession()
SgwCtrl -> GtpSessionsRepo : CreateSession()
GtpSessionsRepo -> GtpSession : make (\n\
  SessionID for you,\n\
  CmdChan for you,\n\
  SgwCtrlSendChan,\n\
  SgwCtrlRecvChan for you\n)
activate GtpSession
GtpSession -> GtpSession : Status:Idle
SgwCtrl <-- GtpSessionsRepo : SessionID, CmdChan

GtpSession -> GtpSession : Wait a CMD
SgwCtrl -> GtpSession : <<CHAN>>\n Dst, Local, CSReq
SgwCtrl -> SgwCtrl : Wait Chan result

GtpSession -> GtpSession : Status:CSReqSending
activate GtpSession #FFBBBB

GtpSession -> SgwCtrl : NextSeq()
GtpSession <-- SgwCtrl : Seq

GtpSession -> SgwCtrlSender : <<CHAN>>\n Dst, Local, MsgBin
SgwCtrlSender -> SgwCtrlSender : Send a UDP packet

GtpSession -> GtpSession : Wait receive (Seq) \n or timeout / retry

SgwCtrlReceiver -> SgwCtrlReceiver : Read a UDP packet
SgwCtrlReceiver -> GtpSessionsRepo : Find (Remote UDPAddr, Local UDPAddr, SgwCtrlTEID)
SgwCtrlReceiver <-- GtpSessionsRepo : SgwCtrlRecvChan for the session
SgwCtrlReceiver -> GtpSession : <<CHAN>> Remote, MsgBin
SgwCtrl <- GtpSession : <<CHAN>> CSReq result

GtpSession -> GtpSession : Status:Connected
deactivate GtpSession

API <-- SgwCtrl : result
Client <-- API : result


@enduml
