consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  CreateGtpsessionPayload:
    example:
      apn: example.com
      ebi: 5
      imsi: "440100123456780"
      mcc: "440"
      mei: "1212345612345612"
      mnc: "10"
      msisdn: "8101012345678"
    properties:
      apn:
        description: Access Point Name
        example: example.com
        format: hostname
        type: string
      ebi:
        default: 5
        description: EPS Bearer ID
        example: 5
        maximum: 15
        minimum: 5
        type: integer
      imsi:
        example: "440100123456780"
        pattern: ^[0-9]{14,15}$
        type: string
      mcc:
        default: "440"
        description: Mobile Country Code
        example: "440"
        pattern: ^[0-9]{3}$
        type: string
      mei:
        description: Mobile Equipment Identifier
        example: "1212345612345612"
        pattern: ^[0-9]{15,16}$
        type: string
      mnc:
        default: "10"
        description: Mobile Network Code
        example: "10"
        pattern: ^[0-9]{2,3}$
        type: string
      msisdn:
        example: "8101012345678"
        pattern: ^[0-9]{12,15}$
        type: string
    required:
    - apn
    - mcc
    - mnc
    - msisdn
    - mei
    - imsi
    - ebi
    title: CreateGtpsessionPayload
    type: object
  Gtpsession:
    description: A GTP session (default view)
    example:
      apn: example.com
      ebi: 5
      fteid:
        pgwCtrlFTEID:
          ipv4: 127.0.0.1
          teid: "0x12345678"
        pgwDataFTEID:
          ipv4: 127.0.0.1
          teid: "0x12345678"
        sgwCtrlFTEID:
          ipv4: 127.0.0.1
          teid: "0x12345678"
        sgwDataFTEID:
          ipv4: 127.0.0.1
          teid: "0x12345678"
      imsi: "440100123456780"
      mcc: "440"
      mei: "1212345612345612"
      mnc: "10"
      msisdn: "8101012345678"
      paa: 93.108.70.217
      sid: 1
    properties:
      apn:
        description: Access Point Name
        example: example.com
        format: hostname
        type: string
      ebi:
        default: 5
        description: EPS Bearer ID
        example: 5
        maximum: 15
        minimum: 5
        type: integer
      fteid:
        $ref: '#/definitions/gtpSessionFTEIDs'
      imsi:
        example: "440100123456780"
        pattern: ^[0-9]{14,15}$
        type: string
      mcc:
        default: "440"
        description: Mobile Country Code
        example: "440"
        pattern: ^[0-9]{3}$
        type: string
      mei:
        description: Mobile Equipment Identifier
        example: "1212345612345612"
        pattern: ^[0-9]{15,16}$
        type: string
      mnc:
        default: "10"
        description: Mobile Network Code
        example: "10"
        pattern: ^[0-9]{2,3}$
        type: string
      msisdn:
        example: "8101012345678"
        pattern: ^[0-9]{12,15}$
        type: string
      paa:
        default: 0.0.0.0
        description: PDN Address Allocation
        example: 93.108.70.217
        format: ipv4
        type: string
      sid:
        description: Session ID in this SGW
        example: 1
        minimum: 0
        type: integer
    required:
    - apn
    - sid
    - imsi
    - mcc
    - mnc
    - mei
    - msisdn
    title: 'Mediatype identifier: application/vnd.gtpsession+json; view=default'
    type: object
  UdpEchoFlowPayload:
    example:
      destAddr: 48.227.40.225
      destPort: 7777
      numOfSend: 1
      recvPacketSize: 1460
      sendPacketSize: 1460
      sourcePort: 7777
      targetBps: 1e+08
      tos: 0
      ttl: 255
    properties:
      destAddr:
        description: ECHO destination IPv4 address
        example: 48.227.40.225
        format: ipv4
        type: string
      destPort:
        default: 7777
        description: ECHO destination UDP port
        example: 7777
        maximum: 65535
        minimum: 0
        type: integer
      numOfSend:
        description: Number of send packets
        example: 1
        minimum: 1
        type: integer
      recvPacketSize:
        description: Receive packet size (including IP header)
        example: 1460
        maximum: 1460
        minimum: 38
        type: integer
      sendPacketSize:
        description: Send packet size (including IP header)
        example: 1460
        maximum: 1460
        minimum: 38
        type: integer
      sourcePort:
        default: 7777
        description: ECHO source UDP port
        example: 7777
        maximum: 65535
        minimum: 0
        type: integer
      targetBps:
        description: Target bitrate(bps) in SGi not S5/S8
        example: 1e+08
        maximum: 1e+11
        minimum: 1
        type: integer
      tos:
        default: 0
        description: Type of service
        example: 0
        maximum: 255
        minimum: 0
        type: integer
      ttl:
        default: 255
        description: Time To Live
        example: 255
        maximum: 255
        minimum: 0
        type: integer
    required:
    - destAddr
    - sendPacketSize
    - targetBps
    - numOfSend
    - recvPacketSize
    title: UdpEchoFlowPayload
    type: object
  Udpechoflow:
    description: A UDP ECHO flow (default view)
    example:
      UdpEchoFlowArg:
        destAddr: 48.227.40.225
        destPort: 7777
        numOfSend: 1
        recvPacketSize: 1460
        sendPacketSize: 1460
        sourcePort: 7777
        targetBps: 1e+08
        tos: 0
        ttl: 255
    properties:
      UdpEchoFlowArg:
        $ref: '#/definitions/UdpEchoFlowPayload'
    title: 'Mediatype identifier: application/vnd.udpechoflow+json; view=default'
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
  fteid:
    example:
      ipv4: 127.0.0.1
      teid: "0x12345678"
    properties:
      ipv4:
        example: 127.0.0.1
        format: ipv4
        type: string
      teid:
        example: "0x12345678"
        pattern: ^0x[0-9A-F]{8}$
        type: string
    required:
    - teid
    - ipv4
    title: fteid
    type: object
  gtpSessionFTEIDs:
    example:
      pgwCtrlFTEID:
        ipv4: 127.0.0.1
        teid: "0x12345678"
      pgwDataFTEID:
        ipv4: 127.0.0.1
        teid: "0x12345678"
      sgwCtrlFTEID:
        ipv4: 127.0.0.1
        teid: "0x12345678"
      sgwDataFTEID:
        ipv4: 127.0.0.1
        teid: "0x12345678"
    properties:
      pgwCtrlFTEID:
        $ref: '#/definitions/fteid'
      pgwDataFTEID:
        $ref: '#/definitions/fteid'
      sgwCtrlFTEID:
        $ref: '#/definitions/fteid'
      sgwDataFTEID:
        $ref: '#/definitions/fteid'
    title: gtpSessionFTEIDs
    type: object
host: localhost:8080
info:
  description: |-
    Gojiko は日本のL2接続MVNOでの利用に適した簡素な疑似SGWシミュレータです。
    Jmeter等で操作可能であるため、試験自動化に適しています。
  title: Gojiko API
  version: ""
paths:
  /sgw/{sgwAddr}/gtpsessions:
    post:
      description: Create a new gtp sesseion
      operationId: gtpsession#create
      parameters:
      - description: SGW GTPv2-C loopback address
        format: ipv4
        in: path
        name: sgwAddr
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateGtpsessionPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.gtpsession+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Gtpsession'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: create gtpsession
      tags:
      - gtpsession
  /sgw/{sgwAddr}/gtpsessions/id/{sid}:
    get:
      description: Show the gtp session by session ID
      operationId: gtpsession#showByID
      parameters:
      - description: SGW GTPv2-C loopback address
        format: ipv4
        in: path
        name: sgwAddr
        required: true
        type: string
      - description: Session ID in this SGW
        in: path
        minimum: 0
        name: sid
        required: true
        type: integer
      produces:
      - application/vnd.goa.error
      - application/vnd.gtpsession+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Gtpsession'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: showByID gtpsession
      tags:
      - gtpsession
  /sgw/{sgwAddr}/gtpsessions/imsi/{imsi}/ebi/{ebi}:
    get:
      description: Show the gtp session by IMSI and EBI
      operationId: gtpsession#showByIMSIandEBI
      parameters:
      - default: 5
        description: EPS Bearer ID
        in: path
        maximum: 15
        minimum: 5
        name: ebi
        required: true
        type: integer
      - in: path
        name: imsi
        pattern: ^[0-9]{14,15}$
        required: true
        type: string
      - description: SGW GTPv2-C loopback address
        format: ipv4
        in: path
        name: sgwAddr
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - application/vnd.gtpsession+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Gtpsession'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: showByIMSIandEBI gtpsession
      tags:
      - gtpsession
  /sgw/{sgwAddr}/gtpsessions/imsi/{imsi}/ebi/{ebi}/udp_echo_flow:
    post:
      description: Start UDP ECHO flow by IMSI and EBI
      operationId: udpEchoFlowByIMSIandEBI#create
      parameters:
      - default: 5
        description: EPS Bearer ID
        in: path
        maximum: 15
        minimum: 5
        name: ebi
        required: true
        type: integer
      - in: path
        name: imsi
        pattern: ^[0-9]{14,15}$
        required: true
        type: string
      - description: SGW GTPv2-C loopback address
        format: ipv4
        in: path
        name: sgwAddr
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UdpEchoFlowPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.udpechoflow+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Udpechoflow'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: create udpEchoFlowByIMSIandEBI
      tags:
      - udpEchoFlowByIMSIandEBI
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Gtpsession'
schemes:
- http
swagger: "2.0"
